name: Workflow A
on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-develop.*'
jobs:
  failed-build:
    runs-on: 'ubuntu-latest'
    steps:
    - run: |
        echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        echo "${{ github.server_url }}"
        echo "${{ github.repository }}"
        sleep 30
        exit 1
