name: Workflow B
on:
  workflow_run:
    workflows: ["Workflow A"]
    types:
      - completed
jobs:
  workflow-a-status:
    runs-on: 'ubuntu-latest'
    steps:
      - run: echo "Workflow A completed with conclusion status = '${{ github.event.workflow_run.conclusion }}'"
