name: Workflow A
on:
  push:
jobs:
  failed-build:
    if: ${{ github.event.workflow_run.conclusion == '' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: 'ubuntu-latest'
    steps:
    - run: |
        echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        echo "${{ github.server_url }}"
        echo "${{ github.repository }}"
        sleep 30
        exit 1
