name: Workflow A
on:
  push:
jobs:
  failed-build:
    if: ${{ github.event.workflow_run.conclusion == '' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: 'ubuntu-latest'
    steps:
    - run: |
        echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        sleep 30
        exit 0
    - if: failure()
      run: |
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          /repos/OWNER/REPO/actions/runs/RUN_ID/rerun
  retrier:
    runs-on: 'ubuntu-latest'
    needs: failed-build
    steps:
    - run: echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
