name: Workflow B
on:
  workflow_run:
    workflows: ["Workflow A"]
    types:
      - completed
jobs:
  workflow-a-status:
    if: ${{ github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.run_attempt <= 3 }}
    runs-on: 'ubuntu-latest'
    steps:
    - env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/rerun"
        echo "${{ github.event.workflow_run.rerun_url }}"
        echo "${{ github.event.workflow_run.run_attempt }}"
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          /repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/rerun
